### PR TITLE
Added AgencyID, AgencyName, ListID.

### PR DESCRIPTION
**Pull request by skinkie**
As discussed in #28.

I have not updated any of the other classes because it seems that the license is not added to the files by running the code. Neither did I update the other versions of the code lists. If you approve this addition I'll update the other versions as well.

### CODE REVIEW

**Comment by phax** [comment]
Thank you - I will change the names slightly so that they are all upper case and replicate it for the other UBL versions as well

**Comment by skinkie** [comment]
@phax would you like it if we add something like this:

```java
    public static QuantityType getQuantyType(EUnitOfMeasureCode21 eUnitOfMeasureCode21, BigDecimal value) {
        QuantityType quantityType = new QuantityType();
        quantityType.setUnitCodeListAgencyName(EUnitOfMeasureCode21.agencyName);
        quantityType.setUnitCodeListAgencyID(EUnitOfMeasureCode21.agencyID);
        quantityType.setUnitCodeListID(EUnitOfMeasureCode21.listID);
        quantityType.setUnitCode(eUnitOfMeasureCode21.getID());
        quantityType.setValue(value);
    }
```

**Comment by phax** [comment]
@skinkie In general that would be valuable but it guess that this is quite an effort to provide this for all 4 supported UBL versions in a "generic" way without bloating dependencies????

**Comment by skinkie** [comment]
> @skinkie In general that would be valuable but it guess that this is quite an effort to provide this for all 4 supported UBL versions in a "generic" way without bloating dependencies????

I wouldn't mind to generate the code at the same place that you use to generate the enumeration classes?

**Comment by phax** [comment]
Okay, and what value class (QuantityType) and enum (EUnitOfMeasureCode21) mappings do you have in mind?

**Comment by skinkie** [comment]
Isn't the only place the unitofmeasurecode is used within the quantitytype?

**Comment by phax** [comment]
That's my problem - where would I look this up. Is there a technical resource where I can retrieve the information from?

**Comment by skinkie** [comment]
@phax I guess the XSD? :-)

**Comment by phax** [comment]
Nope - in the XSD everything is a String. The codelists are provided as separate Genericode files and I am not aware of any linkage between them

**Pull request merged**
