### PR TITLE
Added eforms module

### PR DESCRIPTION
**Pull request by jonatanprins**
PR for #42 

Adds module for TED eForms.

### CODE REVIEW

**Comment by phax** [comment]
Oh. Why this? I just wanted to merge it into the new eforms branch...

**Comment by jonatanprins** [comment]
@phax sorry. Possibly should've been opened from a different account.

**Comment by phax** [comment]
Ah okay. As you like. I have no strong feelings who does it ;-)

**Comment by jonatanprins** [comment]
We're ok. Branch restored.

**Comment by phax** [comment]
@jonatanprins as soon as you remove the draft, I will merge it to a local branch in here

**Pull request merged**
